version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
    - db
    image: 4erdenko/foodgram_backend
    env_file: ../.env
    volumes:
      - static:/app/backend_static
      - media:/app/media

  frontend:
    image: 4erdenko/foodgram_frontend
    command: cp -r /app/build/. /fronted_static/
    volumes:
      - static:/fronted_static
  gateway:
    depends_on:
      - db
      - backend
      - frontend
    image: nginx:latest
    ports:
      - "9001:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
