version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: 4erdenko/foodgram_backend
    env_file: ../.env
    volumes:
      - static:/app/backend_static
      - media:/app/media

  frontend:
    image: 4erdenko/foodgram_frontend
    command: cp -r /app/build/. /fronted_static/
    volumes:
      - static:/fronted_static
  gateway:
    image: nginx:latest
    ports:
      - "9001:80"
    volumes:
      - static:/static
      - media:/media
      - ./config/nginx/conf.d:/etc/nginx/conf.d
